import {
  FaFileImage, FaImage, FaFileArchive, FaObjectGroup, FaSyncAlt, FaTint,
  FaSignature, FaFileAlt, FaThLarge, FaMarkdown, FaBalanceScale, FaUnlock, FaLock,
  FaImages, FaTrash, FaHashtag, FaFileExport, FaInfoCircle, FaRuler, FaCropAlt,
  FaBookmark, FaHighlighter, FaFileWord, FaSlidersH, FaExpandArrowsAlt, FaCompressAlt,
  FaExchangeAlt, FaIdCard, FaCode, FaCut, FaEyeSlash, FaStamp, FaEyeDropper, FaPen,
  FaLaugh, FaLayerGroup, FaUserSlash, FaArrowUp, FaPalette, FaPencilAlt, FaBorderAll,
  FaQrcode, FaClone, FaBarcode, FaCamera, FaWifi, FaAddressCard, FaFilePdf,
  FaHdd, FaFont, FaFingerprint, FaCalendar, FaVolumeUp, FaDollarSign,
  FaKey, FaClock, FaCalculator, FaParagraph, FaTerminal, FaRandom, FaPercent,
  FaHeartbeat, FaMoneyBillWave, FaSortNumericDown, FaTable,
  FaPaintBrush, FaSquare, FaSearch, FaGlobe, FaStopwatch, FaCalendarAlt,
  FaChartLine, FaEye, FaPenFancy, FaFire, FaFileCode, FaDiceD6,
} from 'react-icons/fa'
import type { IconType } from 'react-icons'
import type { ToolDef } from './types'

const IMG = ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/bmp']

export const TOOLS: ToolDef[] = [
  // ---------- PDF ----------
  { id: 'image-to-pdf', slug: 'image-to-pdf', name: 'Image to PDF', short: 'JPG/PNG → PDF', description: 'Combine images into a single PDF document with custom page size, orientation and margins.', category: 'pdf', icon: FaFileImage, accept: IMG, multiple: true, popular: true, keywords: ['jpg', 'png', 'convert', 'photo'] },
  { id: 'pdf-to-image', slug: 'pdf-to-image', name: 'PDF to Image', short: 'PDF → PNG/JPG', description: 'Render every PDF page to high-quality PNG or JPEG images and download as a ZIP.', category: 'pdf', icon: FaImage, accept: ['application/pdf'], popular: true, keywords: ['render', 'png', 'jpg', 'export'] },
  { id: 'compress-pdf', slug: 'compress-pdf', name: 'Compress PDF', short: 'Shrink file size', description: 'Reduce PDF size by re-rasterizing pages at a chosen quality. Target-size mode & analytics.', category: 'pdf', icon: FaFileArchive, accept: ['application/pdf'], popular: true, keywords: ['reduce', 'optimize', 'smaller'] },
  { id: 'merge-pdf', slug: 'merge-pdf', name: 'Merge PDF', short: 'Combine PDFs', description: 'Merge multiple PDFs into one. Drag to reorder, preview thumbnails, edit metadata.', category: 'pdf', icon: FaObjectGroup, accept: ['application/pdf'], multiple: true, popular: true, keywords: ['combine', 'join', 'concat'] },
  { id: 'split-pdf', slug: 'split-pdf', name: 'Split PDF', short: 'Extract ranges', description: 'Split a PDF by page ranges with visual page selection and a range parser.', category: 'pdf', icon: FaCut, accept: ['application/pdf'], popular: true, keywords: ['divide', 'separate', 'range'] },
  { id: 'rotate-pdf', slug: 'rotate-pdf', name: 'Rotate PDF', short: 'Fix orientation', description: 'Rotate pages individually or in batch with live preview rendering.', category: 'pdf', icon: FaSyncAlt, accept: ['application/pdf'], keywords: ['turn', 'orientation', 'landscape'] },
  { id: 'watermark-pdf', slug: 'watermark-pdf', name: 'Watermark PDF', short: 'Add text/image mark', description: 'Stamp text or image watermarks with opacity, rotation and position controls.', category: 'pdf', icon: FaTint, accept: ['application/pdf'], keywords: ['stamp', 'brand', 'overlay'] },
  { id: 'sign-pdf', slug: 'sign-pdf', name: 'Sign PDF', short: 'Draw/type signature', description: 'Add drawn, typed or uploaded signatures and place them on any page.', category: 'pdf', icon: FaSignature, accept: ['application/pdf'], keywords: ['signature', 'esign', 'sign'] },
  { id: 'pdf-to-text', slug: 'pdf-to-text', name: 'PDF to Text', short: 'Extract text', description: 'Extract all selectable text from a PDF, page by page, ready to copy or download.', category: 'pdf', icon: FaFileAlt, accept: ['application/pdf'], keywords: ['ocr', 'extract', 'copy'] },
  { id: 'organize-pdf', slug: 'organize-pdf', name: 'Page Organizer', short: 'Reorder pages', description: 'Reorder, rotate and remove pages on a visual thumbnail board, then rebuild the PDF.', category: 'pdf', icon: FaThLarge, accept: ['application/pdf'], keywords: ['reorder', 'arrange', 'manage'] },
  { id: 'markdown-to-pdf', slug: 'markdown-to-pdf', name: 'Markdown to PDF', short: 'MD → PDF', description: 'Write GitHub-flavored Markdown with live preview and export a styled PDF.', category: 'pdf', icon: FaMarkdown, keywords: ['md', 'document', 'export'] },
  { id: 'compare-pdf', slug: 'compare-pdf', name: 'Compare PDF', short: 'Diff two PDFs', description: 'Compare two PDFs side-by-side with text diff and page-count comparison.', category: 'pdf', icon: FaBalanceScale, accept: ['application/pdf'], multiple: true, keywords: ['diff', 'difference', 'changes'] },
  { id: 'unlock-pdf', slug: 'unlock-pdf', name: 'Unlock PDF', short: 'Remove password', description: 'Remove a known password from an encrypted PDF to create an unprotected copy.', category: 'pdf', icon: FaUnlock, accept: ['application/pdf'], keywords: ['decrypt', 'password', 'open'] },
  { id: 'protect-pdf', slug: 'protect-pdf', name: 'Protect PDF', short: 'Add password', description: 'Encrypt a PDF with a user password to restrict access.', category: 'pdf', icon: FaLock, accept: ['application/pdf'], keywords: ['encrypt', 'password', 'secure'] },
  { id: 'extract-images', slug: 'extract-images', name: 'Extract Images', short: 'Images from PDF', description: 'Pull embedded raster images out of a PDF and download them as a ZIP.', category: 'pdf', icon: FaImages, accept: ['application/pdf'], keywords: ['extract', 'pictures', 'export'] },
  { id: 'delete-pages', slug: 'delete-pages', name: 'Delete Pages', short: 'Remove pages', description: 'Select and delete specific pages from a PDF.', category: 'pdf', icon: FaTrash, accept: ['application/pdf'], keywords: ['remove', 'trim'] },
  { id: 'page-numbers', slug: 'page-numbers', name: 'Add Page Numbers', short: 'Number pages', description: 'Add page numbers with position, format and font-size controls.', category: 'pdf', icon: FaHashtag, accept: ['application/pdf'], keywords: ['pagination', 'footer', 'numbers'] },
  { id: 'extract-pages', slug: 'extract-pages', name: 'Extract Pages', short: 'Keep pages', description: 'Keep only the pages you select and discard the rest.', category: 'pdf', icon: FaFileExport, accept: ['application/pdf'], keywords: ['keep', 'subset'] },
  { id: 'pdf-metadata', slug: 'pdf-metadata', name: 'PDF Metadata', short: 'Edit properties', description: 'View and edit PDF title, author, subject, keywords and producer.', category: 'pdf', icon: FaInfoCircle, accept: ['application/pdf'], keywords: ['properties', 'info', 'title', 'author'] },
  { id: 'pdf-page-size', slug: 'pdf-page-size', name: 'Page Size Converter', short: 'Resize pages', description: 'Convert PDF pages to A4, Letter, A3, Legal and more with scaling.', category: 'pdf', icon: FaRuler, accept: ['application/pdf'], keywords: ['a4', 'letter', 'resize'] },
  { id: 'pdf-crop', slug: 'pdf-crop', name: 'PDF Crop', short: 'Trim margins', description: 'Crop margins from all PDF pages with visual selection and coordinate preview.', category: 'pdf', icon: FaCropAlt, accept: ['application/pdf'], keywords: ['crop', 'trim', 'margin', 'cut'] },
  { id: 'pdf-bookmarks', slug: 'pdf-bookmarks', name: 'PDF Bookmarks', short: 'Add table of contents', description: 'Add, edit and manage bookmarks/table of contents in PDF documents.', category: 'pdf', icon: FaBookmark, accept: ['application/pdf'], keywords: ['bookmark', 'toc', 'outline', 'navigation'] },
  { id: 'pdf-annotate', slug: 'pdf-annotate', name: 'PDF Annotate', short: 'Highlight & underline', description: 'Highlight, underline, and add text annotations to PDF pages.', category: 'pdf', icon: FaHighlighter, accept: ['application/pdf'], popular: true, keywords: ['annotate', 'highlight', 'underline', 'text', 'markup'] },
  { id: 'pdf-to-word', slug: 'pdf-to-word', name: 'PDF to Word', short: 'PDF → DOCX', description: 'Convert PDF documents to editable Word (.docx) files with text extraction.', category: 'pdf', icon: FaFileWord, accept: ['application/pdf'], popular: true, keywords: ['word', 'docx', 'convert', 'editable'] },
  { id: 'pdf-compress-advanced', slug: 'pdf-compress-advanced', name: 'Advanced Compression', short: 'Multi-pass compress', description: 'Advanced PDF compression with DPI control, quality presets, and multi-pass optimization.', category: 'pdf', icon: FaSlidersH, accept: ['application/pdf'], keywords: ['compress', 'optimize', 'dpi', 'quality', 'advanced'] },

  // ---------- IMAGE ----------
  { id: 'resize-image', slug: 'resize-image', name: 'Resize Image', short: 'Change dimensions', description: 'Resize images by pixels or percent with aspect-ratio lock and high-quality scaling.', category: 'image', icon: FaExpandArrowsAlt, accept: IMG, popular: true, keywords: ['scale', 'dimensions', 'pixels'] },
  { id: 'compress-image', slug: 'compress-image', name: 'Compress Image', short: 'Reduce size', description: 'Compress images with before/after slider, quality preview and preset profiles.', category: 'image', icon: FaCompressAlt, accept: IMG, popular: true, keywords: ['optimize', 'smaller', 'quality'] },
  { id: 'convert-image', slug: 'convert-image', name: 'Convert Format', short: 'PNG/JPG/WebP', description: 'Convert between PNG, JPEG, WebP and BMP with quality control.', category: 'image', icon: FaExchangeAlt, accept: IMG, popular: true, keywords: ['webp', 'png', 'jpg', 'format'] },
  { id: 'crop-image', slug: 'crop-image', name: 'Crop & Rotate', short: 'Trim & turn', description: 'Crop with free or fixed aspect ratios and rotate/flip images.', category: 'image', icon: FaCropAlt, accept: IMG, keywords: ['trim', 'cut', 'rotate', 'flip'] },
  { id: 'passport-photo', slug: 'passport-photo', name: 'Passport Photo', short: 'ID photo maker', description: 'Create compliant ID photos (Passport, Visa, Aadhaar, PAN) with guide overlays.', category: 'image', icon: FaIdCard, accept: IMG, keywords: ['id', 'visa', 'aadhaar', 'pan'] },
  { id: 'image-to-base64', slug: 'image-to-base64', name: 'Image to Base64', short: 'Data URI', description: 'Convert an image to a Base64 data URI for inline embedding.', category: 'image', icon: FaCode, accept: IMG, keywords: ['datauri', 'encode', 'inline'] },
  { id: 'remove-background', slug: 'remove-background', name: 'Remove Background', short: 'Cut out subject', description: 'Remove solid/near-solid backgrounds with a chroma threshold and edge feathering.', category: 'image', icon: FaCut, accept: IMG, keywords: ['transparent', 'cutout', 'bg'] },
  { id: 'blur-background', slug: 'blur-background', name: 'Blur Image', short: 'Gaussian blur', description: 'Apply adjustable Gaussian blur — great for backgrounds and privacy.', category: 'image', icon: FaEyeSlash, accept: IMG, keywords: ['blur', 'soften', 'privacy'] },
  { id: 'watermark-image', slug: 'watermark-image', name: 'Watermark Image', short: 'Add text mark', description: 'Add a tiled or single text watermark with opacity and rotation.', category: 'image', icon: FaStamp, accept: IMG, keywords: ['brand', 'overlay', 'copyright'] },
  { id: 'color-picker', slug: 'color-picker', name: 'Color Picker', short: 'Extract palette', description: 'Pick colors from an image and extract a dominant color palette.', category: 'image', icon: FaEyeDropper, accept: IMG, keywords: ['palette', 'eyedropper', 'hex'] },
  { id: 'image-metadata', slug: 'image-metadata', name: 'Image Metadata', short: 'View EXIF', description: 'Inspect EXIF, GPS and camera metadata embedded in your photos.', category: 'image', icon: FaInfoCircle, accept: IMG, keywords: ['exif', 'gps', 'camera'] },
  { id: 'collage-maker', slug: 'collage-maker', name: 'Collage Maker', short: 'Photo grid', description: 'Arrange multiple photos into a grid collage with spacing and background.', category: 'image', icon: FaThLarge, accept: IMG, multiple: true, keywords: ['grid', 'montage', 'photos'] },
  { id: 'image-exif-editor', slug: 'image-exif-editor', name: 'Image Metadata Editor', short: 'View/Remove EXIF', description: 'View and remove EXIF metadata from photos. Protect your privacy by stripping GPS, camera info and other embedded data.', category: 'image', icon: FaPen, accept: IMG, keywords: ['exif', 'metadata', 'gps', 'privacy', 'strip'] },
  { id: 'meme-generator', slug: 'meme-generator', name: 'Meme Generator', short: 'Add text to images', description: 'Add top and bottom text overlays to any image. Custom font size, colors, and stroke width.', category: 'image', icon: FaLaugh, accept: IMG, keywords: ['meme', 'text', 'overlay', 'caption', 'funny'] },
  { id: 'image-compress-batch', slug: 'image-compress-batch', name: 'Batch Image Compressor', short: 'Compress many at once', description: 'Compress multiple images simultaneously with quality control. Download individually or as ZIP.', category: 'image', icon: FaLayerGroup, accept: IMG, multiple: true, keywords: ['compress', 'batch', 'optimize', 'zip'] },
  { id: 'background-remover', slug: 'background-remover', name: 'Background Remover (AI)', short: 'Remove backgrounds', description: 'Remove image backgrounds using AI. Runs entirely in your browser — no server uploads.', category: 'image', icon: FaUserSlash, accept: IMG, popular: true, keywords: ['background', 'remove', 'ai', 'transparent', 'cutout'] },
  { id: 'image-upscaler', slug: 'image-upscaler', name: 'Image Upscaler', short: '2x/3x/4x upscale', description: 'Upscale images to 2x, 3x, or 4x resolution with high-quality smoothing.', category: 'image', icon: FaArrowUp, accept: IMG, keywords: ['upscale', 'resize', 'resolution', 'enlarge', 'hd'] },

  // ---------- QR ----------
  { id: 'qr-generator', slug: 'qr-generator', name: 'QR Generator', short: 'Create QR codes', description: 'Generate QR codes for URL, WiFi, vCard, email, SMS, geo, events and more.', category: 'qr', icon: FaQrcode, popular: true, keywords: ['barcode', 'wifi', 'vcard', 'url'] },
  { id: 'qr-scanner', slug: 'qr-scanner', name: 'QR Scanner', short: 'Read QR codes', description: 'Scan QR codes from your camera or an uploaded image.', category: 'qr', icon: FaSearch, accept: IMG, keywords: ['read', 'decode', 'camera'] },
  { id: 'qr-batch', slug: 'qr-batch', name: 'QR Batch', short: 'Bulk generate', description: 'Generate many QR codes at once from a list and download them as a ZIP.', category: 'qr', icon: FaClone, keywords: ['bulk', 'multiple', 'csv'] },
  { id: 'qr-customizer', slug: 'qr-customizer', name: 'QR Customizer', short: 'Styled QR codes', description: 'Create QR codes with custom colors, gradients, rounded modules, and center logo.', category: 'qr', icon: FaPalette, popular: true, keywords: ['custom', 'gradient', 'logo', 'styled', 'design'] },
  { id: 'barcode-generator', slug: 'barcode-generator', name: 'Barcode Generator', short: 'Code128 / EAN-13 / Code39', description: 'Generate barcodes in Code 128, EAN-13, or Code 39 format with custom colors.', category: 'qr', icon: FaBarcode, keywords: ['barcode', 'code128', 'ean13', 'code39', 'gs1'] },

  // ---------- UTILITY ----------
  { id: 'file-size', slug: 'file-size', name: 'File Size Calculator', short: 'Bytes/KB/MB', description: 'Convert and calculate file sizes across units with transfer-time estimates.', category: 'utility', icon: FaHdd, keywords: ['bytes', 'kb', 'mb', 'units'] },
  { id: 'document-size', slug: 'document-size', name: 'Document Checker', short: 'Inspect files', description: 'Drop any file to inspect its exact size, type and dimensions.', category: 'utility', icon: FaSearch, accept: ['*/*'], keywords: ['inspect', 'check', 'info'] },
  { id: 'base64', slug: 'base64', name: 'Base64 Encode/Decode', short: 'Text & files', description: 'Encode or decode text and files to/from Base64.', category: 'utility', icon: FaCode, keywords: ['encode', 'decode', 'datauri'] },
  { id: 'text-counter', slug: 'text-counter', name: 'Text Counter', short: 'Words & chars', description: 'Count characters, words, sentences, paragraphs and reading time.', category: 'utility', icon: FaFont, keywords: ['word count', 'characters', 'reading time'] },
  { id: 'hash-generator', slug: 'hash-generator', name: 'Hash Generator', short: 'SHA / checksums', description: 'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes of text or files.', category: 'utility', icon: FaFingerprint, keywords: ['sha256', 'checksum', 'md5'] },
  { id: 'age-calculator', slug: 'age-calculator', name: 'Age Calculator', short: 'Birth date → age', description: 'Calculate your exact age in years, months, days, hours and minutes. Find zodiac sign, next birthday, and fun facts.', category: 'utility', icon: FaCalendar, keywords: ['age', 'birthday', 'birth', 'zodiac', 'years'] },
  { id: 'text-to-speech', slug: 'text-to-speech', name: 'Text to Speech', short: '3 TTS engines', description: 'Convert text to speech with 3 engines: Browser Native (instant), Kokoro AI (82M neural, private), and Edge Neural (322+ Microsoft voices, no download). Adjustable rate, pitch, volume.', category: 'utility', icon: FaVolumeUp, keywords: ['tts', 'speech', 'voice', 'accessibility', 'read aloud', 'neural', 'edge', 'kokoro'] },
  { id: 'currency-converter', slug: 'currency-converter', name: 'Currency Converter', short: '170+ currencies', description: 'Real-time exchange rates for 170+ fiat currencies. Rates cached for 1 hour. Swap, favorite currencies, copy results.', category: 'utility', icon: FaDollarSign, popular: true, keywords: ['exchange', 'forex', 'money', 'rate', 'convert'] },
  { id: 'unit-converter', slug: 'unit-converter', name: 'Unit Converter', short: '100+ units', description: 'Convert between 100+ units across 9 categories: length, weight, temperature, area, volume, speed, data, time, angle. Instant real-time conversion.', category: 'utility', icon: FaExchangeAlt, popular: true, keywords: ['measure', 'length', 'weight', 'temperature', 'speed'] },
  { id: 'json-formatter', slug: 'json-formatter', name: 'JSON Formatter', short: 'Validate & format', description: 'Validate, pretty-print, minify, and explore JSON with tree view. Copy or download results. Shows key count, nesting depth, and size stats.', category: 'utility', icon: FaCode, popular: true, keywords: ['json', 'format', 'validate', 'prettify', 'minify', 'beautify'] },
  { id: 'password-generator', slug: 'password-generator', name: 'Password Generator', short: 'Secure random', description: 'Generate cryptographically secure random passwords with strength meter, crack time estimate, presets, and history. Nothing leaves your browser.', category: 'utility', icon: FaKey, popular: true, keywords: ['password', 'random', 'secure', 'crypto', 'generate'] },
  { id: 'timestamp-converter', slug: 'timestamp-converter', name: 'Timestamp Converter', short: 'Unix ↔ Date', description: 'Convert between Unix timestamps and human-readable dates. Live clock, time difference calculator, multiple output formats.', category: 'utility', icon: FaClock, popular: true, keywords: ['unix', 'timestamp', 'date', 'time', 'epoch'] },
  { id: 'base-converter', slug: 'base-converter', name: 'Number Base Converter', short: 'Binary/Hex/Octal', description: 'Convert between binary, octal, decimal, hexadecimal, base32, and base64. Shows binary representation, bit count, and byte size.', category: 'utility', icon: FaTerminal, popular: true, keywords: ['binary', 'hex', 'octal', 'decimal', 'base', 'number'] },
  { id: 'lorem-ipsum', slug: 'lorem-ipsum', name: 'Lorem Ipsum', short: 'Placeholder text', description: 'Generate placeholder text for designs and layouts. Paragraphs, sentences, or words. Wrap in HTML tags.', category: 'utility', icon: FaParagraph, keywords: ['lorem', 'placeholder', 'text', 'dummy'] },
  { id: 'markdown-preview', slug: 'markdown-preview', name: 'Markdown Preview', short: 'MD → HTML', description: 'Write GitHub-flavored Markdown with live preview. Split or full preview mode. Export as HTML.', category: 'utility', icon: FaFileCode, keywords: ['markdown', 'md', 'preview', 'html'] },
  { id: 'color-converter', slug: 'color-converter', name: 'Color Converter', short: 'HEX/RGB/HSL/CMYK', description: 'Convert between HEX, RGB, HSL, CMYK color formats. Pick colors or enter values directly. Shows contrast color.', category: 'utility', icon: FaEyeDropper, keywords: ['color', 'hex', 'rgb', 'hsl', 'cmyk', 'picker'] },
  { id: 'regex-tester', slug: 'regex-tester', name: 'Regex Tester', short: 'Test patterns', description: 'Test regular expressions with live matching, highlighting, group capture, and quick pattern presets.', category: 'utility', icon: FaTerminal, keywords: ['regex', 'pattern', 'match', 'regexp'] },
  { id: 'uuid-generator', slug: 'uuid-generator', name: 'UUID Generator', short: 'v4/v1/Short/Nano', description: 'Generate cryptographically random UUIDs (v4, v1), short IDs, and nano IDs. Batch generate, copy, download.', category: 'utility', icon: FaHashtag, keywords: ['uuid', 'guid', 'random', 'id', 'nano'] },
  { id: 'dice-roller', slug: 'dice-roller', name: 'Dice Roller', short: 'Virtual dice', description: 'Roll virtual dice with custom counts, sides, and modifiers. Track roll history. Supports D&D presets.', category: 'utility', icon: FaDiceD6, keywords: ['dice', 'roll', 'd20', 'd6', 'random'] },
  { id: 'random-number', slug: 'random-number', name: 'Random Generator', short: 'Numbers & strings', description: 'Generate random integers, floats, alphanumeric strings, and number lists. Cryptographically secure.', category: 'utility', icon: FaRandom, keywords: ['random', 'number', 'string', 'generator'] },
  { id: 'tip-calculator', slug: 'tip-calculator', name: 'Tip Calculator', short: 'Bill & split', description: 'Calculate tip percentage, total bill, and split between multiple people. Quick preset percentages.', category: 'utility', icon: FaPercent, keywords: ['tip', 'bill', 'split', 'restaurant'] },
  { id: 'bmi-calculator', slug: 'bmi-calculator', name: 'BMI Calculator', short: 'Body Mass Index', description: 'Calculate BMI with metric or imperial units. Shows category, ideal weight range, and BMI scale visualization.', category: 'utility', icon: FaHeartbeat, keywords: ['bmi', 'health', 'weight', 'body'] },
  { id: 'loan-calculator', slug: 'loan-calculator', name: 'Loan / EMI Calculator', short: 'Monthly payments', description: 'Calculate monthly payments, total interest, and view yearly amortization schedule for mortgages and loans.', category: 'utility', icon: FaMoneyBillWave, keywords: ['loan', 'mortgage', 'emi', 'interest', 'payment'] },
  { id: 'roman-numeral', slug: 'roman-numeral', name: 'Roman Numeral Converter', short: '1–3999', description: 'Convert between decimal numbers and Roman numerals. Supports 1–3999 with reference table.', category: 'utility', icon: FaSortNumericDown, keywords: ['roman', 'numeral', 'convert', 'ancient'] },
  { id: 'scientific-calculator', slug: 'scientific-calculator', name: 'Scientific Calculator', short: 'Trig, log, power', description: 'Full scientific calculator with trigonometry, logarithms, powers, memory, and history.', category: 'utility', icon: FaCalculator, keywords: ['calculator', 'scientific', 'trig', 'log', 'math'] },
  { id: 'heic-converter', slug: 'heic-converter', name: 'HEIC to JPG/PNG', short: 'iPhone converter', description: 'Convert iPhone HEIC/HEIF photos to JPG or PNG. Batch convert, quality control, download.', category: 'image', icon: FaSyncAlt, accept: ['image/heic', 'image/heif'], keywords: ['heic', 'heif', 'iphone', 'convert'] },
  { id: 'text-diff', slug: 'text-diff', name: 'Text Diff Checker', short: 'Compare texts', description: 'Compare two texts with character, word, or line-level diff. Highlights additions and removals.', category: 'utility', icon: FaFileExport, keywords: ['diff', 'compare', 'text', 'difference'] },
  { id: 'color-palette', slug: 'color-palette', name: 'Color Palette Extractor', short: 'From images', description: 'Extract dominant colors from any image. Pick, copy hex/RGB/HSL values, export palettes.', category: 'image', icon: FaPaintBrush, accept: ['image/*'], keywords: ['palette', 'color', 'extract', 'dominant'] },
  { id: 'photo-to-sketch', slug: 'photo-to-sketch', name: 'Photo to Sketch', short: 'Pencil/Ink/Charcoal', description: 'Convert photos to pencil, ink, charcoal, or negative sketch effects with adjustable intensity.', category: 'image', icon: FaPencilAlt, accept: ['image/*'], keywords: ['sketch', 'pencil', 'drawing', 'effect'] },
  { id: 'csv-viewer', slug: 'csv-viewer', name: 'CSV Viewer & Editor', short: 'Sort, search, export', description: 'View, sort, search, and export CSV files. Handles large datasets with pagination.', category: 'utility', icon: FaTable, keywords: ['csv', 'viewer', 'editor', 'data', 'table'] },
  { id: 'qr-scanner-enhanced', slug: 'qr-scanner-enhanced', name: 'QR Scanner (Camera)', short: 'Camera & upload', description: 'Scan QR codes from live camera feed or uploaded images. Auto-detects URLs for quick opening.', category: 'qr', icon: FaCamera, keywords: ['qr', 'scanner', 'camera', 'read', 'decode'] },

  // ---------- UTILITY (Batch 5) ----------
  { id: 'css-gradient-generator', slug: 'css-gradient-generator', name: 'CSS Gradient Generator', short: 'Linear/Radial/Conic', description: 'Create beautiful CSS gradients with live preview. Linear, radial, and conic styles. Copy CSS code.', category: 'utility', icon: FaFire, keywords: ['css', 'gradient', 'linear', 'radial', 'design'] },
  { id: 'box-shadow-generator', slug: 'box-shadow-generator', name: 'Box Shadow Generator', short: 'Multi-shadow CSS', description: 'Design CSS box shadows with multiple layers, inset shadows, and custom colors. Copy ready-to-use code.', category: 'utility', icon: FaSquare, keywords: ['css', 'box-shadow', 'design', 'effect'] },
  { id: 'svg-to-png', slug: 'svg-to-png', name: 'SVG to PNG Converter', short: 'Scale 1-8x', description: 'Convert SVG files to PNG with adjustable scale (1-8x). Transparent background option.', category: 'utility', icon: FaImage, keywords: ['svg', 'png', 'convert', 'raster'] },
  { id: 'image-ocr', slug: 'image-ocr', name: 'Image to Text (OCR)', short: '11 languages', description: 'Extract text from images using Tesseract.js OCR. Supports 11 languages with progress tracking.', category: 'utility', icon: FaSearch, accept: IMG, keywords: ['ocr', 'text', 'extract', 'tesseract'] },
  { id: 'favicon-generator', slug: 'favicon-generator', name: 'Favicon Generator', short: 'All standard sizes', description: 'Generate favicons in all standard sizes (16-512px) plus .ico from any image.', category: 'utility', icon: FaGlobe, accept: IMG, keywords: ['favicon', 'icon', 'ico', 'web'] },
  { id: 'image-border', slug: 'image-border', name: 'Image Border & Frame', short: 'Borders & shadows', description: 'Add borders, rounded corners, and drop shadows to images. Customizable width, color, and style.', category: 'image', icon: FaBorderAll, accept: IMG, keywords: ['border', 'frame', 'shadow', 'rounded'] },

  // ---------- UTILITY (Phase 1) ----------
  { id: 'json-csv', slug: 'json-csv', name: 'JSON ↔ CSV Converter', short: 'Bidirectional', description: 'Convert between JSON and CSV formats instantly. Parse, validate, and download.', category: 'utility', icon: FaExchangeAlt, popular: true, keywords: ['json', 'csv', 'convert', 'data', 'table'] },
  { id: 'stopwatch', slug: 'stopwatch', name: 'Stopwatch & Timer', short: 'Lap tracking', description: 'Precision stopwatch with lap tracking and countdown timer with presets. Never miss a second.', category: 'utility', icon: FaStopwatch, keywords: ['stopwatch', 'timer', 'countdown', 'clock', 'lap'] },
  { id: 'cron-generator', slug: 'cron-generator', name: 'Cron Generator', short: 'Schedule builder', description: 'Build cron expressions visually with next-run preview. Presets for common schedules.', category: 'utility', icon: FaCalendarAlt, keywords: ['cron', 'schedule', 'timer', 'linux', 'job'] },

  // ---------- QR (Phase 1) ----------
  { id: 'wifi-qr', slug: 'wifi-qr', name: 'WiFi QR Code', short: 'Share WiFi', description: 'Generate a QR code for easy WiFi sharing. Supports WPA, WEP, and open networks.', category: 'qr', icon: FaWifi, popular: true, keywords: ['wifi', 'qr', 'share', 'network', 'hotspot'] },
  { id: 'vcard-qr', slug: 'vcard-qr', name: 'vCard QR Code', short: 'Contact card', description: 'Create a QR code containing your contact information for easy sharing.', category: 'qr', icon: FaAddressCard, keywords: ['vcard', 'contact', 'qr', 'business card'] },
  { id: 'qr-to-pdf', slug: 'qr-to-pdf', name: 'QR to PDF', short: 'Export QR as PDF', description: 'Generate multiple QR codes and export them as a printable PDF document.', category: 'qr', icon: FaFileExport, keywords: ['qr', 'pdf', 'export', 'print', 'batch'] },

  // ---------- UTILITY (Phase 4) ----------
  { id: 'currency-chart', slug: 'currency-chart', name: 'Currency Chart', short: 'Rate trends', description: 'Visualize exchange rate trends over time with interactive charts. Historical data and stats.', category: 'utility', icon: FaChartLine, keywords: ['currency', 'chart', 'graph', 'exchange', 'rate', 'trend'] },
  { id: 'color-blindness', slug: 'color-blindness', name: 'Color Blindness Simulator', short: 'See like others', description: 'Simulate how images look to people with protanopia, deuteranopia, tritanopia, or achromatopsia.', category: 'utility', icon: FaEye, accept: IMG, keywords: ['color', 'blindness', 'accessibility', 'vision', 'simulate'] },
  { id: 'text-to-handwriting', slug: 'text-to-handwriting', name: 'Text to Handwriting', short: 'Realistic script', description: 'Convert typed text into realistic handwriting with multiple fonts, ink colors, and paper styles.', category: 'utility', icon: FaPenFancy, keywords: ['handwriting', 'script', 'pen', 'cursive', 'font'] },
  { id: 'heatmap-generator', slug: 'heatmap-generator', name: 'Heatmap Generator', short: 'Data visualization', description: 'Create beautiful heatmap visualizations from numerical data. Multiple colormaps and export.', category: 'utility', icon: FaFire, keywords: ['heatmap', 'visualization', 'data', 'chart', 'color'] },
]

export const CATEGORY_META: Record<string, { label: string; description: string; gradient: string; icon: IconType }> = {
  pdf: { label: 'PDF Tools', description: 'Merge, split, compress, convert & edit PDFs', gradient: 'from-rose-500 to-orange-500', icon: FaFilePdf },
  image: { label: 'Image Tools', description: 'Resize, compress, convert & enhance images', gradient: 'from-brand-500 to-fuchsia-500', icon: FaImage },
  qr: { label: 'QR Tools', description: 'Generate, scan & batch QR codes', gradient: 'from-accent-500 to-emerald-500', icon: FaQrcode },
  utility: { label: 'Utilities', description: 'Handy developer & file utilities', gradient: 'from-amber-500 to-yellow-400', icon: FaSlidersH },
}

export const getTool = (slug: string) => TOOLS.find((t) => t.slug === slug)
export const toolsByCategory = (cat: string) => TOOLS.filter((t) => t.category === cat)
export const popularTools = () => TOOLS.filter((t) => t.popular)
