import { lazy, type LazyExoticComponent, type ComponentType } from 'react'

type ToolComp = LazyExoticComponent<ComponentType>

export const TOOL_COMPONENTS: Record<string, ToolComp> = {
  // PDF
  'merge-pdf': lazy(() => import('./pdf/MergePdf')),
  'split-pdf': lazy(() => import('./pdf/SplitPdf')),
  'image-to-pdf': lazy(() => import('./pdf/ImageToPdf')),
  'pdf-to-image': lazy(() => import('./pdf/PdfToImage')),
  'compress-pdf': lazy(() => import('./pdf/CompressPdf')),
  'rotate-pdf': lazy(() => import('./pdf/RotatePdf')),
  'watermark-pdf': lazy(() => import('./pdf/WatermarkPdf')),
  'sign-pdf': lazy(() => import('./pdf/SignPdf')),
  'pdf-to-text': lazy(() => import('./pdf/PdfToText')),
  'organize-pdf': lazy(() => import('./pdf/OrganizePdf')),
  'markdown-to-pdf': lazy(() => import('./pdf/MarkdownToPdf')),
  'compare-pdf': lazy(() => import('./pdf/ComparePdf')),
  'unlock-pdf': lazy(() => import('./pdf/UnlockPdf')),
  'protect-pdf': lazy(() => import('./pdf/ProtectPdf')),
  'extract-images': lazy(() => import('./pdf/ExtractImages')),
  'delete-pages': lazy(() => import('./pdf/DeletePages')),
  'page-numbers': lazy(() => import('./pdf/PageNumbers')),
  'extract-pages': lazy(() => import('./pdf/ExtractPages')),
  'pdf-metadata': lazy(() => import('./pdf/PdfMetadata')),
  'pdf-page-size': lazy(() => import('./pdf/PdfPageSize')),
  // IMAGE
  'resize-image': lazy(() => import('./image/ResizeImage')),
  'compress-image': lazy(() => import('./image/CompressImage')),
  'convert-image': lazy(() => import('./image/ConvertImage')),
  'crop-image': lazy(() => import('./image/CropImage')),
  'passport-photo': lazy(() => import('./image/PassportPhoto')),
  'image-to-base64': lazy(() => import('./image/ImageToBase64')),
  'remove-background': lazy(() => import('./image/RemoveBackground')),
  'blur-background': lazy(() => import('./image/BlurImage')),
  'watermark-image': lazy(() => import('./image/WatermarkImage')),
  'color-picker': lazy(() => import('./image/ColorPicker')),
  'image-metadata': lazy(() => import('./image/ImageMetadata')),
  'collage-maker': lazy(() => import('./image/CollageMaker')),
  // QR
  'qr-generator': lazy(() => import('./qr/QrGenerator')),
  'qr-scanner': lazy(() => import('./qr/QrScanner')),
  'qr-batch': lazy(() => import('./qr/QrBatch')),
  'qr-customizer': lazy(() => import('./qr/QrCustomizer')),
  'barcode-generator': lazy(() => import('./qr/BarcodeGenerator')),
  // UTILITY
  'file-size': lazy(() => import('./utility/FileSize')),
  'document-size': lazy(() => import('./utility/DocumentSize')),
  'base64': lazy(() => import('./utility/Base64')),
  'text-counter': lazy(() => import('./utility/TextCounter')),
  'hash-generator': lazy(() => import('./utility/HashGenerator')),
  'age-calculator': lazy(() => import('./utility/AgeCalculator')),
  'text-to-speech': lazy(() => import('./utility/TextToSpeech')),
  'currency-converter': lazy(() => import('./utility/CurrencyConverter')),
  'unit-converter': lazy(() => import('./utility/UnitConverter')),
  'json-formatter': lazy(() => import('./utility/JsonFormatter')),
  'password-generator': lazy(() => import('./utility/PasswordGenerator')),
  'timestamp-converter': lazy(() => import('./utility/TimestampConverter')),
  'base-converter': lazy(() => import('./utility/BaseConverter')),
  'lorem-ipsum': lazy(() => import('./utility/LoremIpsum')),
  'markdown-preview': lazy(() => import('./utility/MarkdownPreview')),
  'color-converter': lazy(() => import('./utility/ColorConverter')),
  'regex-tester': lazy(() => import('./utility/RegexTester')),
  'uuid-generator': lazy(() => import('./utility/UuidGenerator')),
  'dice-roller': lazy(() => import('./utility/DiceRoller')),
  'random-number': lazy(() => import('./utility/RandomNumber')),
  'tip-calculator': lazy(() => import('./utility/TipCalculator')),
  'bmi-calculator': lazy(() => import('./utility/BmiCalculator')),
  'loan-calculator': lazy(() => import('./utility/LoanCalculator')),
  'roman-numeral': lazy(() => import('./utility/RomanNumeral')),
  'scientific-calculator': lazy(() => import('./utility/ScientificCalculator')),
  'heic-converter': lazy(() => import('./image/HeicConverter')),
  'text-diff': lazy(() => import('./utility/TextDiff')),
  'color-palette': lazy(() => import('./image/ColorPalette')),
  'photo-to-sketch': lazy(() => import('./image/PhotoToSketch')),
  'csv-viewer': lazy(() => import('./utility/CsvViewer')),
  'qr-scanner-enhanced': lazy(() => import('./qr/QrReader')),
  // Batch 5
  'css-gradient-generator': lazy(() => import('./utility/CssGradientGenerator')),
  'box-shadow-generator': lazy(() => import('./utility/BoxShadowGenerator')),
  'svg-to-png': lazy(() => import('./utility/SvgToPng')),
  'image-ocr': lazy(() => import('./utility/ImageOcr')),
  'favicon-generator': lazy(() => import('./utility/FaviconGenerator')),
  'image-border': lazy(() => import('./image/ImageBorder')),
  // Phase 1
  'json-csv': lazy(() => import('./utility/JsonToCsv')),
  'stopwatch': lazy(() => import('./utility/Stopwatch')),
  'cron-generator': lazy(() => import('./utility/CronGenerator')),
  'wifi-qr': lazy(() => import('./qr/WifiQr')),
  'vcard-qr': lazy(() => import('./qr/VCardQr')),
  'qr-to-pdf': lazy(() => import('./qr/QrToPdf')),
  // Phase 2 - Image
  'image-exif-editor': lazy(() => import('./image/ImageExifEditor')),
  'meme-generator': lazy(() => import('./image/MemeGenerator')),
  'image-compress-batch': lazy(() => import('./image/ImageCompressBatch')),
  'background-remover': lazy(() => import('./image/BackgroundRemover')),
  'image-upscaler': lazy(() => import('./image/ImageUpscaler')),
  // Phase 3 - PDF
  'pdf-crop': lazy(() => import('./pdf/PdfCrop')),
  'pdf-bookmarks': lazy(() => import('./pdf/PdfBookmarks')),
  'pdf-annotate': lazy(() => import('./pdf/PdfAnnotate')),
  'pdf-to-word': lazy(() => import('./pdf/PdfToWord')),
  'pdf-compress-advanced': lazy(() => import('./pdf/PdfCompressAdvanced')),
  // Phase 4 - Utility
  'currency-chart': lazy(() => import('./utility/CurrencyChart')),
  'color-blindness': lazy(() => import('./utility/ColorBlindnessSimulator')),
  'text-to-handwriting': lazy(() => import('./utility/TextToHandwriting')),
  'heatmap-generator': lazy(() => import('./utility/HeatmapGenerator')),
}
